# Generated by Django 5.0.6 on 2024-06-06 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floodzones', '0003_comment_floodimage_description_floodimage_taken_at_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='floodimage',
            name='floodzones__latitud_5caad9_idx',
        ),
        migrations.AlterField(
            model_name='floodimage',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
